#!/usr/bin/env python

import argparse
from PIL import Image
from toolbox import wordio
import prepare_features as pf
import preprocess_otsu


from recognizer_seq2seq import recognize_seq2seq
import blstm_ctc_net

data_set = None

def parse_args():
    parser = argparse.ArgumentParser(description='CTC recognizer')


    parser.add_argument('input_image', type=str, nargs=1, metavar='INPUT_IMAGE')
    parser.add_argument('input_words', type=str, nargs=1, metavar='INPUT_WORDS')
    parser.add_argument('output_words', type=str, nargs=1, metavar='OUTPUT_WORDS')

    input_args = parser.parse_args()

    data_set = "KNMP" if "KNMP" in input_args.input_words[0] else "STANFORD"
    n_image_rnn_steps = 50
    text_lines, word_boxes, images_data, images_length = prepare_data(input_args.input_image[0], input_args.input_words[0], n_image_rnn_steps,
                                                                      feature_count=16, resize_ratio=0.25)
    predicted_words = recognize_seq2seq(data_set, images_data, images_length, word_boxes, n_image_rnn_steps)
    save_results(text_lines, word_boxes, predicted_words, input_args.output_words[0])


def prepare_data(page_file_path, input_words_file_path, n_image_rnn_steps, feature_count, resize_ratio, otsufy=True):
    # Read PPM
    page_image = Image.open(page_file_path)
    print("Page:", page_file_path)
    print("Page image size:", page_image.width, "x", page_image.height)
    print("Input words:",input_words_file_path)

    # Read .words file to get word boxes
    text_lines, image_name = wordio.read(input_words_file_path)

    word_boxes = []
    images_data = []
    images_length = []
    for text_line in text_lines:
        for word_box in text_line:
            word_boxes.append(word_box)
            box = (word_box.left, word_box.top, word_box.right, word_box.bottom)
            word_image = page_image.crop(box)
            if otsufy:
                word_image = preprocess_otsu.otsufy_pillow_image(word_image)
            preprocessed_word_image = pf.preprocess_image(word_image, feature_count, resize_ratio=resize_ratio)
            image_data = pf.get_feature_data_for_image(preprocessed_word_image)
            image_len = len(image_data)
            if image_len > n_image_rnn_steps:
                image_len = n_image_rnn_steps
            image_data = pf.get_data_with_fixed_time_step_count(image_data, n_image_rnn_steps)
            images_data.append(image_data)
            images_length.append(image_len)

    return text_lines, word_boxes, images_data, images_length


def save_results(text_lines, word_boxes, predicted_words, output_path):
    for word_b, predicted_w in zip(word_boxes, predicted_words):
        word_b.text = predicted_w

    wordio.save(text_lines, output_path)


if __name__ == "__main__":
    parse_args()
